version: 2

project_name: purgable

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: purgable

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    formats: ["tar.gz"]
    files:
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

brews:
  - name: purgable
    repository:
      owner: Hxmbl
      name: homebrew-tap
    commit_author:
      name: hxmbl
      email: hxmbl@users.noreply.github.com
    homepage: "https://github.com/Hxmbl/purgable"
    description: "Recursively find files named exactly PURGABLE and ask before deleting them."
    license: MIT
    test: |
      system "#{bin}/purgable --help"
    skip_upload: true
